Repository npm/cli, pull requests merged in 2018-08, with the labels that each got.

#8 config: accept auth tokens from environment variables
  lib/config/get-credentials-by-uri.js
Labels: semver:minor

#39 colors@1.1.2
  node_modules/colors/LICENSE
  node_modules/colors/README.md
  node_modules/colors/examples/normal-usage.js
  node_modules/colors/examples/safe-string.js
  node_modules/colors/index.d.ts
  node_modules/colors/lib/colors.js
  node_modules/colors/lib/custom/trap.js
  node_modules/colors/lib/custom/zalgo.js
  node_modules/colors/lib/extendStringPrototype.js
  node_modules/colors/lib/index.js
  node_modules/colors/lib/maps/america.js
  node_modules/colors/lib/maps/rainbow.js
  node_modules/colors/lib/maps/random.js
  node_modules/colors/lib/maps/zebra.js
  node_modules/colors/lib/styles.js
  node_modules/colors/lib/system/has-flag.js
  node_modules/colors/lib/system/supports-colors.js
  node_modules/colors/package.json
  node_modules/colors/safe.d.ts
  node_modules/colors/safe.js
  node_modules/colors/themes/generic-logging.js
  package-lock.json
Labels: semver:patch

#31 feature: configurable audit level
  doc/misc/npm-config.md
  lib/audit.js
  lib/config/defaults.js
  test/tap/audit.js
Labels: security, semver:minor

#14 added a header for usage with process.env
  doc/misc/npm-scripts.md
Labels: docs

#60 Docs: mention --otp flag when prompting for OTP
  lib/utils/read-user-info.js
Labels: docs

#62 Set lowercase headers for NPM audit requests
  lib/install/audit.js
Labels: semver:patch

#57 ci: backronym ci to clean-install
  doc/cli/npm-ci.md
  lib/config/cmd-list.js
Labels: semver:minor

#58 version: fix -S argument passing for sign-git-commit
  lib/version.js
Labels: semver:patch
