Repository npm/cli, pull requests merged in 2018-11, with the labels that each got.

#70 Automatically audit dependency licenses
  .licensee.json
  .travis.yml
  package-lock.json
  package.json
Labels: semver:patch

#72 bash_completion.d dir found in /etc not /usr/local
  doc/cli/npm-completion.md
Labels: docs, semver:patch

#74 Update OTP documentation for dist-tag add
  doc/cli/npm-dist-tag.md
Labels: docs

#75 edit: scoped packages
  doc/cli/npm-edit.md
  lib/edit.js
Labels: semver:patch

#78 Correct spelling mistakes
  CHANGELOG.md
  changelogs/CHANGELOG-2.md
  changelogs/CHANGELOG-3.md
  changelogs/CHANGELOG-4.md
  changelogs/CHANGELOG-5.md
  doc/misc/npm-registry.md
  lib/install/mutate-into-logical-tree.js
  test/need-npm5-update/lifecycle-signal.js
  test/tap/config-basic.js
  test/tap/ls-depth-cli.js
  test/tap/ls-depth-unmet.js
  test/tap/unit-deps-earliestInstallable.js
Labels: docs, semver:patch

#80 Close the file descriptor if exiting upload via an error.
  lib/publish.js
Labels: semver:patch

#81 feat(cli, outdated): Adds 'Homepage' to outdated --long output.
  doc/cli/npm-outdated.md
  lib/outdated.js
  test/tap/outdated-long.js
Labels: semver:minor

#82 Note that "prepare" runs when installing git dependencies
  doc/misc/npm-scripts.md
Labels: docs

#83 Specify that --dry-run isn't available in older versions of npm publish
  doc/cli/npm-publish.md
Labels: docs

#96 docs: fix tag in inline code
  doc/misc/npm-scripts.md
Labels: docs
