Repository npm/cli, pull requests merged in 2019-02, with the labels that each got.

#151 access: ls-collaborators is ok with non-scoped
  lib/access.js
  test/tap/access.js
Labels: semver:patch

#86 Fix issue with sub folder local references
  lib/install/inflate-shrinkwrap.js
  lib/shrinkwrap.js
  test/tap/install-at-sub-path-locally.js
  test/tap/shrinkwrap-local-dependency.js
  test/tap/spec-local-specifiers.js
Labels: semver:patch

#160 doc: add npm add as alias to npm install
  doc/cli/npm-install.md
Labels: docs

#162 updating link to RFC #10 in the changelog
  CHANGELOG.md
Labels: docs

#139 Check run script existence with undefined
  lib/run-script.js
Labels: semver:minor

#132 error-message: strip version info from pkg on E404
  lib/utils/error-message.js
  test/tap/404.js
Labels: in-progress, semver:patch

#115 install: match git semver ranges
  lib/install/deps.js
  test/tap/dedupe-git-semver.js
Labels: semver:minor

#90 Add support for time-traveling installs.
  doc/misc/npm-config.md
  lib/config/defaults.js
  lib/install.js
  test/tap/install-before.js
Labels: in-progress, semver:minor
