Repository npm/cli, pull requests merged in 2019-01, with the labels that each got.

#123 Handle git branch references correctly
  lib/shrinkwrap.js
Labels: semver:patch

#128 audit: report any errors above 400 as potentially not supporting audit
  lib/audit.js
Labels: semver:patch

#124 cli,outdated: default homepage to an empty string
  lib/outdated.js
Labels: semver:patch

#116 doc: fix npm-prefix description
  doc/cli/npm-prefix.md
Labels: docs

#145 ls: show installed but unmet peer deps
  lib/ls.js
  test/tap/ls-peer.js
Labels: semver:minor

#140 doc: update package.json docs to include repository.directory details
  doc/files/package.json.md
Labels: docs

#149 token: use figgy-config to make sure extra opts are there
  lib/token.js
  test/tap/unit-token-validate-cidr.js
Labels: semver:patch
