Repository npm/cli, pull requests merged in 2020-12, with the labels that each got.

#2275 test: add lib/update.js tests
  lib/update.js
  test/lib/update.js
Labels: Release 7.x, Release-Next

#2237 feat: add npm set-script
  docs/content/commands/npm-set-script.md
  lib/set-script.js
  lib/utils/cmd-list.js
  tap-snapshots/test-lib-utils-cmd-list.js-TAP.test.js
  test/coverage-map.js
  test/lib/set-script.js
Labels: Release 7.x, Release-Next, semver:minor

#2269 test: add lib/uninstall.js tests
  lib/uninstall.js
  test/lib/uninstall.js
Labels: Release 7.x, Release-Next

#2271 docs: don't wrap code block
  docs/content/commands/npm-dist-tag.md
Labels: Release 7.x, Release-Next

#2279 chore: remove unused files
  lib/utils/depr-check.js
  lib/utils/package-id.js
  lib/utils/pick-manifest-from-registry-metadata.js
  lib/utils/save-stack.js
  lib/utils/unix-format-path.js
  lib/utils/warn-deprecated.js
Labels: Release 7.x, Release-Next

#2293 test: add lib/shrinkwrap.js tests
  lib/shrinkwrap.js
  test/lib/shrinkwrap.js
Labels: Release 7.x, Release-Next

#2302 refactor deprecate command and add tests
  lib/deprecate.js
  test/lib/deprecate.js
Labels: Release 7.x, Release-Next

#2304 fix: minor tweaks to lib/unpublish.js
  lib/unpublish.js
  test/lib/unpublish.js
Labels: Release 7.x, Release-Next

#2325 fix: npm search include/exclude
  lib/search.js
  package-lock.json
  package.json
  tap-snapshots/test-lib-search.js-TAP.test.js
  test/fixtures/libnpmsearch-stream-result.js
  test/lib/search.js
Labels: Release 7.x, Release-Next

#2313 minor cleanup of completion command and add tests
  lib/completion.js
  test/lib/completion.js
Labels: Release 7.x, Release-Next

#2314 fix: lib/team.js tweaks and tests
  lib/team.js
  tap-snapshots/test-lib-team.js-TAP.test.js
  test/lib/team.js
Labels: Release 7.x, Release-Next

#2316 ci: run install scripts for root project
  lib/ci.js
  test/lib/ci.js
Labels: Release 7.x, Release-Next

#2323 tests for npm doctor
  lib/doctor.js
  test/lib/doctor.js
Labels: Release 7.x, Release-Next

#2332 Dependencies cleanup
  package-lock.json
  package.json
Labels: Release 7.x, Release-Next

#2366 Include prerelease versions when deprecating an entire package.
  docs/content/commands/npm-deprecate.md
  lib/deprecate.js
  test/lib/deprecate.js
Labels: Needs Review, Release 7.x, Release-Next

#2373 fix: npm profile refactor
  lib/profile.js
  tap-snapshots/test-lib-profile.js-TAP.test.js
  test/lib/profile.js
Labels: Release 7.x, Release-Next

#2381 (docs,test): assorted typo fixes
  CHANGELOG.md
  docs/content/using-npm/scripts.md
  tap-snapshots/test-lib-config.js-TAP.test.js
  tap-snapshots/test-lib-ls.js-TAP.test.js
  test/fixtures/eresolve-explanations.js
  test/lib/config.js
  test/lib/dist-tag.js
  test/lib/ls.js
  test/lib/owner.js
  test/lib/utils/replace-info.js
Labels: Needs Review, Release 7.x

#2382 remove the metrics sender
  docs/content/using-npm/config.md
  lib/npm.js
  lib/utils/config.js
  lib/utils/error-handler.js
  lib/utils/flat-options.js
  lib/utils/metrics-launch.js
  lib/utils/metrics.js
  tap-snapshots/test-lib-utils-config.js-TAP.test.js
  tap-snapshots/test-lib-utils-flat-options.js-TAP.test.js
  test/lib/npm.js
  test/lib/utils/error-handler.js
  test/lib/utils/flat-options.js
Labels: Release 7.x, Release-Next
