Repository npm/cli, pull requests merged in 2021-01, with the labels that each got.

#2444 Remove process.umask() call from config default
  lib/utils/config.js
  tap-snapshots/test-lib-utils-config.js-TAP.test.js
  test/lib/utils/config.js
Labels: Needs Review, Release 7.x, Release-Next, semver:patch

#2417 Change url
  README.md
Labels: Release 7.x, Release-Next, semver:patch

#2422 fix: npm publish --dry-run should not check login status
  lib/publish.js
  test/lib/publish.js
Labels: Release 7.x, Release-Next, semver:patch

#2436 Grammatical Fix in npm-ls Documentation
  docs/content/commands/npm-ls.md
Labels: Release 7.x, Release-Next, semver:patch

#2440 Updated the url for RFC 19 so that it isn't a 404.
  lib/update.js
Labels: Release 7.x, Release-Next, semver:patch

#2448 pass extra arguments directly to run-script as an array
  lib/exec.js
  test/lib/exec.js
Labels: Release 7.x, Release-Next, semver:patch

#2455 fix(ci): pay attention to --ignore-scripts
  lib/ci.js
  test/lib/ci.js
  test/lib/install.js
Labels: Release 7.x, Release-Next, semver:patch

#2456 add foreground-scripts option
  docs/content/using-npm/config.md
  lib/utils/config.js
  lib/utils/flat-options.js
  tap-snapshots/test-lib-utils-config.js-TAP.test.js
  tap-snapshots/test-lib-utils-flat-options.js-TAP.test.js
Labels: Release 7.x, Release-Next

#2498 docs(npm): update `npm` docs
  docs/content/commands/npm.md
Labels: Release 7.x, Release-Next, semver:patch

#2523 chore(tests): skip coverage for results.sort
  lib/help-search.js
Labels: Release 7.x, Release-Next, semver:patch

#2542 fix(docs): add caching docs to exec, init
  docs/content/commands/npm-exec.md
  docs/content/commands/npm-init.md
  docs/content/commands/npm-search.md
Labels: Release 7.x, Release-Next, semver:patch

#2558 docs: refreshed npm updated docs
  docs/content/commands/npm-update.md
Labels: Release 7.x, Release-Next

#2565 docs(npm): update npm command docs
  docs/content/commands/npm.md
Labels: Release 7.x, Release-Next

#2566 docs: refresh npm run-script docs
  docs/content/commands/npm-run-script.md
Labels: Release 7.x, Release-Next

#2564 fix: json-parse-even-better-errors dep listing
  package-lock.json
  package.json
Labels: Release 7.x, Release-Next

#1319 npm diff
  docs/content/commands/npm-diff.md
  docs/content/using-npm/config.md
  lib/diff.js
  lib/utils/cmd-list.js
  lib/utils/config.js
  lib/utils/flat-options.js
  node_modules/.gitignore
  node_modules/@npmcli/disparity-colors/CHANGELOG.md
  node_modules/@npmcli/disparity-colors/LICENSE
  node_modules/@npmcli/disparity-colors/README.md
  node_modules/@npmcli/disparity-colors/index.js
  node_modules/@npmcli/disparity-colors/package.json
  node_modules/binary-extensions/binary-extensions.json
  node_modules/binary-extensions/binary-extensions.json.d.ts
  node_modules/binary-extensions/index.d.ts
  node_modules/binary-extensions/index.js
  node_modules/binary-extensions/license
  node_modules/binary-extensions/package.json
  node_modules/binary-extensions/readme.md
  node_modules/libnpmdiff/CHANGELOG.md
  node_modules/libnpmdiff/LICENSE
  node_modules/libnpmdiff/README.md
  node_modules/libnpmdiff/index.js
  node_modules/libnpmdiff/lib/format-diff.js
  node_modules/libnpmdiff/lib/should-print-patch.js
  node_modules/libnpmdiff/lib/untar.js
  node_modules/libnpmdiff/node_modules/diff/CONTRIBUTING.md
  node_modules/libnpmdiff/node_modules/diff/LICENSE
  node_modules/libnpmdiff/node_modules/diff/README.md
  node_modules/libnpmdiff/node_modules/diff/dist/diff.js
  node_modules/libnpmdiff/node_modules/diff/lib/convert/dmp.js
  node_modules/libnpmdiff/node_modules/diff/lib/convert/xml.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/array.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/base.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/character.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/css.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/json.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/line.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/sentence.js
  node_modules/libnpmdiff/node_modules/diff/lib/diff/word.js
  node_modules/libnpmdiff/node_modules/diff/lib/index.es6.js
  node_modules/libnpmdiff/node_modules/diff/lib/index.js
  node_modules/libnpmdiff/node_modules/diff/lib/index.mjs
  node_modules/libnpmdiff/node_modules/diff/lib/patch/apply.js
  node_modules/libnpmdiff/node_modules/diff/lib/patch/create.js
  node_modules/libnpmdiff/node_modules/diff/lib/patch/merge.js
  node_modules/libnpmdiff/node_modules/diff/lib/patch/parse.js
  node_modules/libnpmdiff/node_modules/diff/lib/util/array.js
  node_modules/libnpmdiff/node_modules/diff/lib/util/distance-iterator.js
  node_modules/libnpmdiff/node_modules/diff/lib/util/params.js
  node_modules/libnpmdiff/node_modules/diff/package.json
  node_modules/libnpmdiff/node_modules/diff/release-notes.md
  node_modules/libnpmdiff/node_modules/diff/runtime.js
  node_modules/libnpmdiff/package.json
  package-lock.json
  package.json
  tap-snapshots/test-lib-utils-cmd-list.js-TAP.test.js
  tap-snapshots/test-lib-utils-config.js-TAP.test.js
  tap-snapshots/test-lib-utils-flat-options.js-TAP.test.js
  test/lib/diff.js
Labels: Release 7.x, Release-Next, semver:minor
