Repository npm/cli, pull requests merged in 2021-07, with the labels that each got.

#3508 fix(config): fix noproxy
  lib/utils/config/definitions.js
  test/lib/utils/config/definitions.js
Labels: Release 7.x, semver:patch

#3499 fix(update-notifier): don't force black background
  lib/utils/update-notifier.js
  tap-snapshots/test/lib/utils/update-notifier.js.test.cjs
Labels: Release 7.x, semver:patch

#3497 fix(usage): better audit/boolean flag usage output
  docs/content/commands/npm-ci.md
  docs/content/commands/npm-dedupe.md
  docs/content/commands/npm-find-dupes.md
  docs/content/commands/npm-install-ci-test.md
  docs/content/commands/npm-install-test.md
  docs/content/commands/npm-install.md
  docs/content/commands/npm-link.md
  docs/content/commands/npm-update.md
  docs/content/using-npm/config.md
  lib/ci.js
  lib/install-ci-test.js
  lib/utils/config/definition.js
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/utils/config/definition.js
Labels: Release 7.x, semver:patch

#3495 fix(publish): obey --ignore-scripts flag
  lib/publish.js
  test/lib/publish.js
Labels: Release 7.x, semver:patch

#3479 chore(exit): log any un-ended timings
  lib/base-command.js
  lib/npm.js
  lib/utils/exit-handler.js
  lib/utils/perf.js
  test/lib/utils/exit-handler.js
Labels: Release 7.x, Release-Next, semver:patch

#3482 chore(refactor): refactor exit handler and tests
  lib/npm.js
  lib/utils/exit-handler.js
  lib/utils/perf.js
  lib/utils/update-notifier.js
  tap-snapshots/test/lib/utils/exit-handler.js.test.cjs
  test/fixtures/mock-npm.js
  test/lib/npm.js
  test/lib/utils/exit-handler.js
  test/lib/utils/perf.js
Labels: Release 7.x

#3540 fix(bundle-and-ignore): case sensitivity cleanup
  node_modules/.gitignore
  node_modules/socks/typings/common/receivebuffer.d.ts
  scripts/bundle-and-gitignore-deps.js
Labels: Release 7.x, Release-Next, semver:patch

#3523 updated policy urls - v7
  CONTRIBUTING.md
  docs/content/commands/npm-unpublish.md
  docs/content/commands/npm.md
  docs/content/using-npm/registry.md
  packages/libnpmdiff/README.md
Labels: Release 7.x

#3463 fix(tests): move more tests to use real npm
  lib/set.js
  lib/test.js
  node_modules/.gitignore
  package-lock.json
  package.json
  test/fixtures/mock-npm.js
  test/lib/find-dupes.js
  test/lib/get.js
  test/lib/load-all.js
  test/lib/prefix.js
  test/lib/prune.js
  test/lib/restart.js
  test/lib/root.js
  test/lib/set.js
  test/lib/start.js
  test/lib/stop.js
  test/lib/test.js
  test/lib/whoami.js
Labels: Release 7.x, semver:patch
