Repository npm/cli, pull requests merged in 2021-08, with the labels that each got.

#3621 fix(docs): do not include certain files
  docs/content/configuring-npm/package-json.md
Labels: semver:patch, Release 7.x, Release-Next

#3630 fix(docs): update npm-publish access flag info
  docs/content/commands/npm-publish.md
Labels: semver:patch, Release 7.x

#3569 deps: remove byte-size
  lib/utils/format-bytes.js
  lib/utils/tar.js
  lib/view.js
  node_modules/byte-size/LICENSE
  node_modules/byte-size/dist/index.js
  node_modules/byte-size/index.mjs
  node_modules/byte-size/package.json
  package-lock.json
  package.json
  tap-snapshots/test/lib/view.js.test.cjs
  test/lib/utils/tar.js
Labels: semver:patch, Release 7.x

#3615 Added nvm-windows to installers links
  README.md
Labels: semver:patch, Release 7.x

#3640 fix(did-you-mean): switch levenshtein libraries
  lib/utils/did-you-mean.js
  node_modules/fastest-levenshtein/LICENSE.md
  node_modules/fastest-levenshtein/index.d.ts
  node_modules/fastest-levenshtein/index.js
  node_modules/fastest-levenshtein/package.json
  node_modules/fastest-levenshtein/test.js
  node_modules/leven/index.d.ts
  node_modules/leven/index.js
  node_modules/leven/license
  node_modules/leven/package.json
  node_modules/leven/readme.md
  package-lock.json
  package.json
Labels: semver:patch, Release 7.x

#3654 fix(docs): revert auto-generated portion of docs
  docs/content/commands/npm-publish.md
Labels: semver:patch, Release 7.x

#3592 add cache commands "ls" and "rm"
  lib/cache.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/cache.js
Labels: semver:minor, Release 7.x

#3664 chore: update config snapshot when manually making docs
  Makefile
  package.json
Labels: semver:patch, Release 7.x

#3681 chore(docs): added clarification on lack of uninstall lifecycle scripts
  docs/content/using-npm/scripts.md
Labels: semver:patch, Release 7.x
