Repository npm/cli, pull requests merged in 2021-03, with the labels that each got.

#2690 fix(docs): update scripts docs
  docs/content/using-npm/scripts.md
Labels: Release 7.x, Release-Next, semver:patch

#2766 Remove unused arguments on various function calls
  lib/access.js
  lib/ls.js
  lib/npm.js
  lib/profile.js
  lib/whoami.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
Labels: Release 7.x, Release-Next, semver:patch

#2789 Get correct npm prefix on all Windows unix shells
  bin/npm
  bin/npx
  test/bin/windows-shims.js
  test/coverage-map.js
  test/lib/doctor.js
  test/lib/npm.js
Labels: Release 7.x, Release-Next, semver:patch

#2803 fix(search): don't pass unused args
  lib/search.js
Labels: Release 7.x, Release-Next, semver:patch

#2807 Feature: explain command shows "bundled" flag for edge
  lib/utils/explain-dep.js
  tap-snapshots/test-lib-utils-explain-dep.js-TAP.test.js
  test/lib/utils/explain-dep.js
Labels: Release 7.x, Release-Next, semver:patch

#2809 Update republish timeout after unpublish
  docs/content/commands/npm-unpublish.md
Labels: Release 7.x, Release-Next, semver:patch

#2822 fix(diff): set option "where" for pacote
  lib/diff.js
  test/lib/diff.js
Labels: Release 7.x, Release-Next, semver:patch

#2851 chore: skip publishing some unnecessary files
  .npmignore
Labels: Needs Review, Release 7.x, semver:patch

#2855 usage: Correct "npm COMMAND help" to "npm help COMMAND"
  lib/base-command.js
  tap-snapshots/test-lib-dist-tag.js-TAP.test.js
  tap-snapshots/test-lib-publish.js-TAP.test.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
Labels: Release 7.x, Release-Next, semver:patch

#2878 Configuration Definition Refactor, Phase 1
  lib/utils/config.js
  lib/utils/flat-options.js
  tap-snapshots/test-lib-utils-config.js-TAP.test.js
  tap-snapshots/test-lib-utils-flat-options.js-TAP.test.js
  test/lib/utils/config.js
  test/lib/utils/flat-options.js
Labels: Release 7.x

#2860 docs(configuring-npm): Fix broken link
  docs/content/configuring-npm/package-json.md
Labels: Release 7.x, Release-Next, semver:patch

#2869 bump version in v7 bug template
  .github/ISSUE_TEMPLATE/bug_7.md
Labels: Release 7.x, Release-Next

#2872 Docs: add asdf-nodejs as a viable version manager
  README.md
Labels: Release 7.x, Release-Next, semver:patch

#2876 Update test-coverage command
  CONTRIBUTING.md
Labels: Release 7.x, Release-Next, semver:patch

#2881 docs(package-json): document default main behavior
  docs/content/configuring-npm/package-json.md
Labels: Release 7.x, Release-Next, semver:patch

#2864 feat: add run-script workspaces
  docs/content/commands/npm-adduser.md
  docs/content/commands/npm-bin.md
  docs/content/commands/npm-cache.md
  docs/content/commands/npm-completion.md
  docs/content/commands/npm-config.md
  docs/content/commands/npm-deprecate.md
  docs/content/commands/npm-doctor.md
  docs/content/commands/npm-edit.md
  docs/content/commands/npm-explore.md
  docs/content/commands/npm-help-search.md
  docs/content/commands/npm-help.md
  docs/content/commands/npm-hook.md
  docs/content/commands/npm-logout.md
  docs/content/commands/npm-org.md
  docs/content/commands/npm-owner.md
  docs/content/commands/npm-ping.md
  docs/content/commands/npm-prefix.md
  docs/content/commands/npm-profile.md
  docs/content/commands/npm-run-script.md
  docs/content/commands/npm-search.md
  docs/content/commands/npm-shrinkwrap.md
  docs/content/commands/npm-star.md
  docs/content/commands/npm-stars.md
  docs/content/commands/npm-team.md
  docs/content/commands/npm-token.md
  docs/content/commands/npm-unstar.md
  docs/content/commands/npm-whoami.md
  docs/content/using-npm/workspaces.md
  lib/base-command.js
  lib/cli.js
  lib/npm.js
  lib/run-script.js
  lib/utils/config/definitions.js
  lib/utils/did-you-mean.js
  lib/utils/lifecycle-cmd.js
  test/lib/npm.js
  test/lib/run-script.js
  test/lib/utils/did-you-mean.js
  test/lib/utils/lifecycle-cmd.js
Labels: Release 7.x, Release-Next, semver:minor

#2908 fix(usage): tie usage to config
  docs/content/using-npm/config.md
  lib/adduser.js
  lib/audit.js
  lib/base-command.js
  lib/bin.js
  lib/fund.js
  lib/install.js
  lib/logout.js
  lib/pack.js
  lib/ping.js
  lib/prune.js
  lib/publish.js
  lib/root.js
  lib/search.js
  lib/uninstall.js
  lib/update.js
  lib/utils/config/definition.js
  lib/utils/config/definitions.js
  lib/whoami.js
  tap-snapshots/test-lib-publish.js-TAP.test.js
  tap-snapshots/test-lib-utils-config-definitions.js-TAP.test.js
  tap-snapshots/test-lib-utils-config-describe-all.js-TAP.test.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
  test/lib/load-all-commands.js
  test/lib/set-script.js
  test/lib/shrinkwrap.js
  test/lib/utils/config/definition.js
Labels: Release 7.x, Release-Next, semver:patch

#2886 feat: add exec workspaces
  docs/content/commands/npm-exec.md
  lib/exec.js
  lib/run-script.js
  lib/workspaces/get-workspaces.js
  test/lib/exec.js
  test/lib/workspaces/get-workspaces.js
Labels: Release 7.x, Release-Next, semver:minor

#2929 fix(install): ignore auditLevel
  lib/install.js
  test/lib/install.js
Labels: Release 7.x, semver:patch

#2948 fix(changelog): correct versions in changelog
  CHANGELOG.md
Labels: Release 7.x, Release-Next

#2950 fix: npm config warn on workspaces
  lib/config.js
  test/lib/config.js
Labels: Release 7.x, Release-Next, semver:patch

#2951 fix(config): accept explicit production=false
  lib/utils/config/definitions.js
  tap-snapshots/test-lib-utils-config-describe-all.js-TAP.test.js
  test/lib/utils/config/definitions.js
Labels: Release 7.x, Release-Next, semver:patch

#2737 Fix CVE-2020-7774
  node_modules/y18n/CHANGELOG.md
  node_modules/y18n/index.js
  node_modules/y18n/package.json
  package-lock.json
Labels: Needs Review, Release 6.x, Security, semver:patch

#2949 Fix manNumberRegex in help.js
  lib/help.js
  test/lib/help.js
Labels: Release 7.x, Release-Next, semver:patch

#2958 Always set npm.command to canonical command name
  lib/npm.js
  test/lib/npm.js
Labels: Release 7.x, Release-Next, semver:patch

#2959 add smoke tests
  .github/workflows/ci.yml
  .npmignore
  Makefile
  package.json
  smoke-tests/content/abbrev.json
  smoke-tests/content/abbrev.min.json
  smoke-tests/content/abbrev/-/abbrev-1.0.4.tgz
  smoke-tests/content/abbrev/-/abbrev-1.1.1.tgz
  smoke-tests/content/promise-all-reject-late.json
  smoke-tests/content/promise-all-reject-late.min.json
  smoke-tests/content/promise-all-reject-late/-/promise-all-reject-late-1.0.1.tgz
  smoke-tests/index.js
  smoke-tests/server.js
  tap-snapshots/smoke-tests-index.js-TAP.test.js
Labels: Release 7.x, Release-Next

#2964 fix(config): properly translate user-agent
  lib/utils/config/definitions.js
  test/lib/utils/config/definitions.js
Labels: Release 7.x, Release-Next, semver:patch

#2965 fix(config): tie save-exact/save-prefix together
  lib/utils/config/definitions.js
  test/lib/utils/config/definitions.js
  test/lib/utils/config/flatten.js
Labels: Release 7.x, Release-Next, semver:patch

#2979 change 'maxsockets' default value back to 50
  docs/content/using-npm/config.md
  lib/utils/config/definitions.js
  tap-snapshots/test-lib-utils-config-describe-all.js-TAP.test.js
Labels: Release 7.x, Release-Next, semver:patch

#3001 feat(view): add workspace support
  docs/content/commands/npm-view.md
  lib/view.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
  tap-snapshots/test-lib-view.js-TAP.test.js
  test/lib/view.js
Labels: Release 7.x, Release-Next, semver:minor
