Repository npm/cli, pull requests merged in 2021-06, with the labels that each got.

#3360 fix(docs): link foreground-scripts w/ loglevel
  docs/content/using-npm/config.md
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
Labels: Release 7.x, Release-Next, semver:patch

#3364 fix(tests): mock writeFile in pack tests
  test/lib/pack.js
Labels: Release 7.x

#3365 chore(package) Use a "files" list
  .npmignore
  package.json
Labels: Release 7.x, Release-Next, semver:patch

#3383 fix(login): properly save scope if defined
  lib/adduser.js
Labels: Release 7.x, Release-Next, semver:patch

#3368 feat(diff): add workspace support
  docs/content/commands/npm-diff.md
  lib/diff.js
  lib/utils/config/definition.js
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/diff.js
Labels: Release 7.x, Release-Next, semver:minor

#3392 docs(workspaces): update using npm section
  docs/content/using-npm/workspaces.md
Labels: Release 7.x, Release-Next, semver:patch

#3399 fix(link): do not prune packages
  lib/link.js
  test/lib/link.js
Labels: Release 7.x, Release-Next, semver:patch

#3386 chore(libnpmdiff): added as workspace
  .github/workflows/ci.yml
  node_modules/libnpmdiff
  package-lock.json
  package.json
  packages/libnpmdiff/.eslintrc.json
  packages/libnpmdiff/.gitignore
  packages/libnpmdiff/CHANGELOG.md
  packages/libnpmdiff/LICENSE
  packages/libnpmdiff/README.md
  packages/libnpmdiff/index.js
  packages/libnpmdiff/lib/format-diff.js
  packages/libnpmdiff/lib/should-print-patch.js
  packages/libnpmdiff/lib/tarball.js
  packages/libnpmdiff/lib/untar.js
  packages/libnpmdiff/package.json
  packages/libnpmdiff/tap-snapshots/test/format-diff.js.test.cjs
  packages/libnpmdiff/tap-snapshots/test/index.js.test.cjs
  packages/libnpmdiff/tap-snapshots/test/untar.js.test.cjs
  packages/libnpmdiff/test/fixtures/archive.tgz
  packages/libnpmdiff/test/fixtures/ruyadorno-simplistic-pkg-with-folders-1.0.0.tgz
  packages/libnpmdiff/test/fixtures/simple-output-2.2.1.tgz
  packages/libnpmdiff/test/format-diff.js
  packages/libnpmdiff/test/index.js
  packages/libnpmdiff/test/should-print-patch.js
  packages/libnpmdiff/test/tarball.js
  packages/libnpmdiff/test/untar.js
  scripts/bundle-and-gitignore-deps.js
Labels: Release 7.x, semver:patch

#3388 chore(refactor): finish passing npm context
  lib/cli.js
  lib/utils/cache-file.js
  lib/utils/error-handler.js
  lib/utils/error-message.js
  lib/utils/explain-eresolve.js
  lib/utils/setup-log.js
  tap-snapshots/test/lib/utils/error-handler.js.test.cjs
  tap-snapshots/test/lib/utils/explain-eresolve.js.test.cjs
  test/lib/cli.js
  test/lib/load-all.js
  test/lib/utils/error-handler.js
  test/lib/utils/error-message.js
  test/lib/utils/explain-eresolve.js
  test/lib/utils/setup-log.js
Labels: Release 7.x, semver:patch

#3418 fix(config): update link definition
  docs/content/commands/npm-ls.md
  docs/content/using-npm/config.md
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
Labels: Release 7.x, Release-Next, semver:patch

#3430 fix(config): add flatOptions.npxCache
  lib/exec.js
  lib/init.js
  lib/utils/config/definitions.js
  test/lib/exec.js
  test/lib/init.js
  test/lib/utils/config/definitions.js
Labels: Release 7.x, Release-Next, semver:patch

#3420 feat(pack): add pack-destination config
  docs/content/commands/npm-pack.md
  docs/content/using-npm/config.md
  lib/pack.js
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/pack.js
Labels: Release 7.x, Release-Next, semver:minor

#3450 fix(docs): Improve phrasing of workspace example
  docs/content/using-npm/workspaces.md
Labels: Release 7.x, Release-Next, semver:patch

#3454 chore(ls): linting cleanup
  bin/npx-cli.js
  lib/ls.js
  package.json
Labels: Release 7.x, Release-Next, semver:patch

#3416 chore(errorHandler): rename to exit handler
  lib/cli.js
  lib/utils/exit-handler.js
  lib/utils/explain-eresolve.js
  tap-snapshots/test/lib/utils/exit-handler.js.test.cjs
  test/lib/cli.js
  test/lib/explore.js
  test/lib/load-all.js
  test/lib/utils/exit-handler.js
Labels: Release 7.x, Release-Next, semver:patch

#3451 chore(refactor): async npm.load
  lib/cli.js
  lib/npm.js
  lib/utils/perf.js
  lib/utils/proc-log-listener.js
  test/lib/cli.js
  test/lib/npm.js
  test/lib/utils/exit-handler.js
Labels: Release 7.x, semver:patch

#3458 chore(tests): expose real mock npm object
  test/fixtures/mock-npm.js
  test/lib/audit.js
  test/lib/bin.js
  test/lib/birthday.js
  test/lib/cache.js
  test/lib/ci.js
  test/lib/cli.js
  test/lib/dedupe.js
  test/lib/diff.js
  test/lib/dist-tag.js
  test/lib/docs.js
  test/lib/exec.js
  test/lib/fund.js
  test/lib/help-search.js
  test/lib/init.js
  test/lib/install.js
  test/lib/link.js
  test/lib/load-all-commands.js
  test/lib/logout.js
  test/lib/ls.js
  test/lib/npm.js
  test/lib/outdated.js
  test/lib/owner.js
  test/lib/pack.js
  test/lib/ping.js
  test/lib/profile.js
  test/lib/publish.js
  test/lib/rebuild.js
  test/lib/repo.js
  test/lib/run-script.js
  test/lib/search.js
  test/lib/set-script.js
  test/lib/shrinkwrap.js
  test/lib/star.js
  test/lib/uninstall.js
  test/lib/unpublish.js
  test/lib/update.js
  test/lib/utils/read-package-name.js
  test/lib/version.js
  test/lib/view.js
  test/lib/whoami.js
Labels: Release 7.x, Release-Next, semver:patch

#3459 chore(config): snapshot config descriptions
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  test/lib/utils/config/definitions.js
Labels: Release 7.x, Release-Next, semver:patch

#3455 chore: @npmcli/package-json refactor
  lib/init.js
  lib/set-script.js
  node_modules/@npmcli/package-json/LICENSE
  node_modules/@npmcli/package-json/lib/index.js
  node_modules/@npmcli/package-json/lib/update-dependencies.js
  node_modules/@npmcli/package-json/lib/update-scripts.js
  node_modules/@npmcli/package-json/lib/update-workspaces.js
  node_modules/@npmcli/package-json/package.json
  package-lock.json
  package.json
  test/lib/init.js
  test/lib/set-script.js
Labels: Release 7.x, Release-Next, semver:patch

#3469 fix(exitHandler): write code to logfile
  lib/utils/exit-handler.js
  tap-snapshots/test/lib/utils/exit-handler.js.test.cjs
  test/lib/utils/exit-handler.js
Labels: Release 7.x, Release-Next, semver:patch

#3474 fix(ping): make "npm ping" echo a right time
  lib/ping.js
Labels: Release 7.x, Release-Next, semver:patch
