Repository npm/cli, pull requests merged in 2021-04, with the labels that each got.

#3013 fix(docs): add workspaces configuration
  docs/content/commands/npm-docs.md
  docs/content/commands/npm-repo.md
  docs/content/commands/npm-set-script.md
  lib/docs.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
Labels: Release 7.x, Release-Next, semver:patch

#3032 feat: workspaces support for dist-tag
  docs/content/commands/npm-dist-tag.md
  lib/dist-tag.js
  tap-snapshots/test-lib-dist-tag.js-TAP.test.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
  test/lib/dist-tag.js
Labels: Release 7.x, Release-Next, semver:minor

#3033 feat(pack): add workspace support
  docs/content/commands/npm-pack.md
  lib/pack.js
  lib/view.js
  tap-snapshots/test-lib-utils-npm-usage.js-TAP.test.js
  tap-snapshots/test-lib-view.js-TAP.test.js
  test/fixtures/mock-npm.js
  test/lib/pack.js
Labels: Release 7.x, Release-Next, semver:minor

#3052 feat(bugs): fallback to email, if provided, when URL is not available
  docs/content/commands/npm-bugs.md
  lib/bugs.js
  test/lib/bugs.js
Labels: Release 7.x, Release-Next, semver:minor

#3140 ls: do not warn on missing optional deps
  lib/ls.js
  package-lock.json
  package.json
  tap-snapshots/test/lib/ls.js.test.cjs
  test/lib/ls.js
Labels: Release 7.x, Release-Next, semver:patch

#3146 docs: mention `directories.bin` in `bin`
  docs/content/configuring-npm/package-json.md
Labels: Release 7.x, Release-Next, semver:patch

#3156 fix: make prune rule work on case-senstive file systems
  node_modules/mkdirp/readme.markdown
Labels: Bug, Release 7.x, Release-Next, semver:patch
