Repository npm/cli, pull requests merged in 2021-02, with the labels that each got.

#2557 docs: npm team revamp
  docs/content/commands/npm-team.md
Labels: Release 7.x, Release-Next

#2569 remove dev dep from checked in modules
  node_modules/require-from-string/index.js
  node_modules/require-from-string/license
  node_modules/require-from-string/package.json
  node_modules/require-from-string/readme.md
Labels: Release 7.x, Release-Next

#2572 doc: add note about --force overriding peer dependencies
  docs/content/using-npm/config.md
Labels: Release 7.x, Release-Next

#2574 ignore the sort in help-search more broadly
  lib/help-search.js
Labels: Release 7.x, Release-Next

#2587 pass all settings through to pacote.packument in outdated
  lib/outdated.js
Labels: Release 7.x, Release-Next

#2573 wrap a timer around the rimraf call in npm-ci
  lib/ci.js
  test/lib/ci.js
Labels: Release 7.x, Release-Next

#2602 fix(publish): follow all configs for registry auth check
  test/lib/publish.js
Labels: Release 7.x, Release-Next

#2613 pass -q to curl calls to disable user .curlrc files
  README.md
  scripts/install.sh
Labels: Release 7.x, Release-Next

#2654 [fix] node v10.0 lacks `fs.promises`
  .github/workflows/ci.yml
  lib/shrinkwrap.js
  lib/utils/reify-finish.js
  test/lib/shrinkwrap.js
  test/lib/utils/reify-finish.js
Labels: Release 7.x

#2688 fix: shrinkwrap in node v10.0
  lib/shrinkwrap.js
Labels: Release 7.x, Release-Next, semver:patch

#2698 docs: mention nodenv in README.md
  README.md
Labels: Release 7.x, Release-Next, semver:patch

#2711 docs: validate that the docs can be parsed by mdx
  docs/dockhand.js
  node_modules/.gitignore
  package-lock.json
  package.json
Labels: Release 7.x, Release-Next, semver:patch

#2718 restore the prefix on output from `npm version <inc>`
  lib/version.js
  test/lib/version.js
Labels: Release 7.x, Release-Next, semver:patch

#2716 throw an error when trying to dedupe in global mode
  lib/dedupe.js
  test/lib/dedupe.js
Labels: Release 7.x, Release-Next, semver:patch

#2717 chore(tests): refactor publish tests
  test/lib/publish.js
Labels: Release 7.x, Release-Next, semver:patch

#2719 fix(runScript): obey silent loglevel
  lib/ci.js
  lib/install.js
  lib/publish.js
  lib/run-script.js
Labels: Release 7.x, Release-Next, semver:patch

#2729 test: fix typo in shrinkwrap.js
  test/lib/shrinkwrap.js
Labels: Release 7.x, Release-Next

#2743 Isaacs/hide easter egg better
  lib/birthday.js
  lib/utils/cmd-list.js
  tap-snapshots/test-lib-utils-cmd-list.js-TAP.test.js
  test/lib/birthday.js
Labels: Release 7.x, Release-Next, semver:patch

#2749 Capitalize Package in a Heading
  docs/content/using-npm/developers.md
Labels: Release 7.x, Release-Next, semver:patch

#2782 test: update hidden package-lock mtime in ls test
  test/lib/ls.js
Labels: Release 7.x, Release-Next, semver:patch
