Repository npm/cli, pull requests merged in 2021-05, with the labels that each got.

#3098 feat(cache): accept multiple specs
  docs/content/commands/npm-cache.md
  lib/cache.js
  test/lib/cache.js
Labels: Release 7.x, Release-Next, semver:minor

#3182 fix(docs): fix broken links
  docs/content/commands/npm-ci.md
  docs/content/commands/npm-dedupe.md
  docs/content/commands/npm-deprecate.md
  docs/content/commands/npm-explore.md
  docs/content/commands/npm-find-dupes.md
  docs/content/commands/npm-install.md
  docs/content/commands/npm-unpublish.md
  docs/content/commands/npm-view.md
  docs/content/commands/npm.md
  docs/content/configuring-npm/folders.md
  docs/content/configuring-npm/package-json.md
  docs/content/using-npm/scripts.md
Labels: Release 7.x, Release-Next, semver:patch

#3187 feat: add workspaces boolean to user-agent
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
  test/lib/utils/config/definitions.js
Labels: Release 7.x, Release-Next, semver:minor

#3201 fix(tests): increase test fuzziness
  test/lib/utils/update-notifier.js
Labels: Release 7.x, Release-Next, semver:patch

#3203 Avoid locale-specific string sorting issues
  lib/config.js
  lib/help.js
  lib/ls.js
  lib/outdated.js
  lib/utils/completion/installed-deep.js
  lib/utils/config/describe-all.js
  lib/utils/npm-usage.js
  lib/utils/tar.js
  package.json
  scripts/bundle-and-gitignore-deps.js
  scripts/config-doc.js
  tap-snapshots/test/lib/config.js.test.cjs
  tap-snapshots/test/lib/ls.js.test.cjs
  tap-snapshots/test/lib/outdated.js.test.cjs
  tap-snapshots/test/lib/utils/tar.js.test.cjs
  test/lib/config.js
  test/lib/exec.js
  test/lib/link.js
  test/lib/load-all-commands.js
  test/lib/ls.js
  test/lib/outdated.js
  test/lib/utils/cleanup-log-files.js
  test/lib/utils/completion/installed-deep.js
  test/lib/utils/tar.js
Labels: Release 7.x, Release-Next, semver:patch

#3211 fix(tests): use config defaults
  lib/outdated.js
  test/fixtures/mock-npm.js
  test/lib/dist-tag.js
  test/lib/view.js
Labels: Release 7.x, Release-Next, semver:patch

#3209 fix(view): fix git specs
  lib/view.js
  tap-snapshots/test/lib/view.js.test.cjs
  test/lib/view.js
Labels: Release 7.x, Release-Next, semver:patch

#3237 fix: lint all files in lib/ folder
  package.json
Labels: Release 7.x, Release-Next, semver:patch

#3231 feat(publish): add workspace support
  docs/content/commands/npm-publish.md
  lib/publish.js
  tap-snapshots/test/lib/publish.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/publish.js
Labels: Release 7.x, Release-Next, semver:minor

#3241 feat: add fund workspaces
  docs/content/commands/npm-fund.md
  lib/fund.js
  lib/workspaces/arborist-cmd.js
  tap-snapshots/test/lib/fund.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/fund.js
  test/lib/workspaces/arborist-cmd.js
Labels: Release 7.x, Release-Next, semver:minor

#3265 feat(explain): add workspaces support
  docs/content/commands/npm-explain.md
  lib/explain.js
  lib/utils/explain-dep.js
  tap-snapshots/test/lib/utils/explain-dep.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/explain.js
  test/lib/utils/explain-dep.js
Labels: Release 7.x, Release-Next, semver:minor

#3227 Add workspaces functionality to reify commands
  docs/content/commands/npm-audit.md
  docs/content/commands/npm-dedupe.md
  docs/content/commands/npm-find-dupes.md
  docs/content/commands/npm-install-test.md
  docs/content/commands/npm-install.md
  docs/content/commands/npm-prune.md
  docs/content/commands/npm-rebuild.md
  docs/content/commands/npm-uninstall.md
  docs/content/commands/npm-update.md
  lib/audit.js
  lib/base-command.js
  lib/ci.js
  lib/dedupe.js
  lib/find-dupes.js
  lib/install.js
  lib/prune.js
  lib/rebuild.js
  lib/uninstall.js
  lib/update.js
  lib/workspaces/arborist-cmd.js
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/update.js
  test/lib/workspaces/arborist-cmd.js
Labels: Release 7.x, Release-Next, semver:minor

#3253 fix(docs): search description typo
  lib/search.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
Labels: Release 7.x, Release-Next, semver:patch

#3217 feat(pack): add --json support
  docs/content/commands/npm-pack.md
  lib/pack.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/pack.js
Labels: Release 7.x, Release-Next, semver:minor

#3250 feat(ls): add workspaces support
  docs/content/commands/npm-ls.md
  lib/ls.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/ls.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/ls.js
Labels: Release 7.x, Release-Next, semver:minor

#3282 fix(docs): proper postinstall script file name
  docs/content/using-npm/scripts.md
Labels: Release 7.x, Release-Next, semver:patch

#3272 ls: show relative paths from root, not absolute
  lib/ls.js
  tap-snapshots/test/lib/ls.js.test.cjs
  test/lib/ls.js
Labels: Release 7.x, Release-Next, semver:patch

#3304 fix(completion): restore IFS even if `npm completion` returns error
  lib/utils/completion.sh
Labels: Release 7.x, Release-Next, semver:patch

#3307 fix(docs) typo package-lock.json docs
  docs/content/configuring-npm/package-lock-json.md
Labels: Release 7.x, Release-Next, semver:patch

#3311 fix: set audit exit code properly
  lib/utils/reify-output.js
  test/lib/utils/reify-output.js
Labels: Release 7.x, Release-Next, semver:patch

#3285 fix(publish): skip private workspaces
  lib/publish.js
  tap-snapshots/test/lib/publish.js.test.cjs
  test/lib/publish.js
Labels: Release 7.x, Release-Next, semver:patch

#3294 ci: add cli dep workflow
  .github/workflows/create-cli-deps-pr.yml
  .gitignore
Labels: Release-Next, semver:patch
