Repository npm/cli, pull requests merged in 2022-08, with the labels that each got.

#5164 fix: when filtering workspaces, make sure the edge has a to before checking if its a workspace
  lib/commands/ls.js
  tap-snapshots/test/lib/commands/ls.js.test.cjs
  test/lib/commands/ls.js
Labels: semver:patch

#5000 feat: add npm query cmd
  docs/content/commands/npm-query.md
  docs/content/using-npm/dependency-selectors.md
  docs/nav.yml
  lib/commands/query.js
  lib/utils/cmd-list.js
  node_modules/@npmcli/query/LICENSE
  node_modules/@npmcli/query/lib/index.js
  node_modules/@npmcli/query/package.json
  node_modules/cssesc/LICENSE-MIT.txt
  node_modules/cssesc/bin/cssesc
  node_modules/cssesc/cssesc.js
  node_modules/cssesc/man/cssesc.1
  node_modules/cssesc/package.json
  node_modules/postcss-selector-parser/API.md
  node_modules/postcss-selector-parser/LICENSE-MIT
  node_modules/postcss-selector-parser/dist/index.js
  node_modules/postcss-selector-parser/dist/parser.js
  node_modules/postcss-selector-parser/dist/processor.js
  node_modules/postcss-selector-parser/dist/selectors/attribute.js
  node_modules/postcss-selector-parser/dist/selectors/className.js
  node_modules/postcss-selector-parser/dist/selectors/combinator.js
  node_modules/postcss-selector-parser/dist/selectors/comment.js
  node_modules/postcss-selector-parser/dist/selectors/constructors.js
  node_modules/postcss-selector-parser/dist/selectors/container.js
  node_modules/postcss-selector-parser/dist/selectors/guards.js
  node_modules/postcss-selector-parser/dist/selectors/id.js
  node_modules/postcss-selector-parser/dist/selectors/index.js
  node_modules/postcss-selector-parser/dist/selectors/namespace.js
  node_modules/postcss-selector-parser/dist/selectors/nesting.js
  node_modules/postcss-selector-parser/dist/selectors/node.js
  node_modules/postcss-selector-parser/dist/selectors/pseudo.js
  node_modules/postcss-selector-parser/dist/selectors/root.js
  node_modules/postcss-selector-parser/dist/selectors/selector.js
  node_modules/postcss-selector-parser/dist/selectors/string.js
  node_modules/postcss-selector-parser/dist/selectors/tag.js
  node_modules/postcss-selector-parser/dist/selectors/types.js
  node_modules/postcss-selector-parser/dist/selectors/universal.js
  node_modules/postcss-selector-parser/dist/sortAscending.js
  node_modules/postcss-selector-parser/dist/tokenTypes.js
  node_modules/postcss-selector-parser/dist/tokenize.js
  node_modules/postcss-selector-parser/dist/util/ensureObject.js
  node_modules/postcss-selector-parser/dist/util/getProp.js
  node_modules/postcss-selector-parser/dist/util/index.js
  node_modules/postcss-selector-parser/dist/util/stripComments.js
  node_modules/postcss-selector-parser/dist/util/unesc.js
  node_modules/postcss-selector-parser/package.json
  node_modules/postcss-selector-parser/postcss-selector-parser.d.ts
  package-lock.json
  smoke-tests/tap-snapshots/test/index.js.test.cjs
  tap-snapshots/test/lib/commands/completion.js.test.cjs
  tap-snapshots/test/lib/commands/query.js.test.cjs
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/npm.js.test.cjs
  tap-snapshots/test/lib/utils/cmd-list.js.test.cjs
  test/lib/commands/query.js
  workspaces/arborist/lib/node.js
  workspaces/arborist/lib/query-selector-all.js
  workspaces/arborist/package.json
  workspaces/arborist/test/node.js
  workspaces/arborist/test/query-selector-all.js
Labels: semver:minor, Agenda, ws:arborist

#4860 feat: add --replace-registry-host=<npmjs|always|never>
  docs/content/using-npm/config.md
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/commands/config.js.test.cjs
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
  workspaces/arborist/lib/arborist/index.js
  workspaces/arborist/lib/arborist/reify.js
  workspaces/arborist/test/arborist/index.js
  workspaces/arborist/test/arborist/reify.js
  workspaces/arborist/test/fixtures/tnock.js
Labels: semver:minor

#5292 fix(docs): remove unnecessary indentation in `npm link` examples
  docs/content/commands/npm-link.md
Labels: semver:patch, Documentation

#5329 fix: update `index.js` spelling error in comment
  workspaces/arborist/lib/arborist/index.js
Labels: semver:patch
