Repository npm/cli, pull requests merged in 2022-04, with the labels that each got.

#4674 deps: @npmcli/metavuln-calculator@3.1.0
  node_modules/@npmcli/metavuln-calculator/lib/advisory.js
  node_modules/@npmcli/metavuln-calculator/package.json
  package-lock.json
Labels: Dependencies

#4678 fix(run-script): don't cascade if-present config
  docs/content/commands/npm-run-script.md
  docs/content/using-npm/config.md
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
Labels: semver:patch, Release 8.x

#4743 deps: npm-registry-fetch@13.1.1
  node_modules/npm-registry-fetch/lib/errors.js
  node_modules/npm-registry-fetch/package.json
  package-lock.json
  package.json
Labels: Dependencies

#4777 fix(libnpmexec): fix read mixed local/registry pkg
  test/lib/commands/exec.js
  workspaces/libnpmexec/lib/index.js
  workspaces/libnpmexec/lib/manifest-missing.js
  workspaces/libnpmexec/test/manifest-missing.js
Labels: semver:patch, Release 8.x, release: next

#4679 fix(install): do not install invalid package name
  lib/commands/install.js
  test/lib/commands/install.js
Labels: semver:patch, Release 8.x, release: next

#4643 fix(libnpmexec): workspaces support
  lib/commands/exec.js
  test/lib/commands/exec.js
  workspaces/libnpmexec/test/index.js
Labels: semver:patch, Release 8.x, release: next

#4784 chore(exec): fix tests
  test/lib/commands/exec.js
Labels: semver:patch, Release 8.x, release: next

#4657 fix(libnpmpublish): unpublish from custom reg
  workspaces/libnpmpublish/lib/unpublish.js
  workspaces/libnpmpublish/test/unpublish.js
Labels: semver:patch, Release 8.x, release: next
