Repository npm/cli, pull requests merged in 2022-03, with the labels that each got.

#4476 fix: set proper workspace repo urls in package.json
  docs/package.json
  workspaces/arborist/package.json
  workspaces/libnpmaccess/package.json
  workspaces/libnpmdiff/package.json
  workspaces/libnpmexec/package.json
  workspaces/libnpmfund/package.json
  workspaces/libnpmhook/package.json
  workspaces/libnpmorg/package.json
  workspaces/libnpmpack/package.json
  workspaces/libnpmpublish/package.json
  workspaces/libnpmsearch/package.json
  workspaces/libnpmteam/package.json
  workspaces/libnpmversion/package.json
Labels: ws:libnpmhook, ws:arborist, ws:libnpmdiff, ws:libnpmaccess, ws:libnpmexec, ws:libnpmorg, ws:libnpmpack, ws:libnpmpublish, ws:libnpmsearch, ws:libnpmteam, ws:libnpmversion, ws:libnpmfund

#4528 fix: clean up owner command and otplease
  lib/commands/owner.js
  lib/utils/otplease.js
Labels: semver:patch, Release 8.x, Release-Next

#4530 deps: make-fetch-happen@10.0.5
  node_modules/make-fetch-happen/lib/agent.js
  node_modules/make-fetch-happen/node_modules/lru-cache/bundle/main.js
  node_modules/make-fetch-happen/node_modules/lru-cache/index.js
  node_modules/make-fetch-happen/node_modules/lru-cache/package.json
  node_modules/make-fetch-happen/package.json
  package-lock.json
  package.json
Labels: semver:patch, Release 8.x, Release-Next

#4531 deps: read-package-json@4.1.2
  node_modules/read-package-json/package.json
  node_modules/read-package-json/read-json.js
  package-lock.json
  package.json
Labels: semver:patch, Release 8.x, Release-Next

#4543 deps: gauge@4.0.3
  node_modules/gauge/lib/demo.js
  node_modules/gauge/package.json
  package-lock.json
Labels: semver:patch, Release 8.x, Release-Next

#4529 fix(rebuild): don't run lifecycle scripts twice on linked deps
  workspaces/arborist/lib/arborist/rebuild.js
Labels: semver:patch, Release 8.x, Release-Next

#4545 deps: map-workspaces@2.0.2
  node_modules/@npmcli/map-workspaces/lib/index.js
  node_modules/@npmcli/map-workspaces/package.json
  package-lock.json
  package.json
Labels: semver:patch, Release 8.x, Release-Next

#4261 fix(arborist) _findMissingEdges missing dependency due to inconsistent path separators
  workspaces/arborist/lib/arborist/load-actual.js
  workspaces/arborist/test/arborist/load-actual.js
Labels: ws:arborist

#4578 fix(arborist): save workspace version
  workspaces/arborist/lib/arborist/reify.js
  workspaces/arborist/tap-snapshots/test/arborist/reify.js.test.cjs
  workspaces/arborist/test/arborist/reify.js
Labels: semver:patch, Release 8.x, Release-Next

#4588 feat(version): reify on workspace version change
  docs/content/commands/npm-version.md
  docs/content/using-npm/config.md
  lib/commands/version.js
  lib/utils/config/definitions.js
  tap-snapshots/test/lib/commands/config.js.test.cjs
  tap-snapshots/test/lib/commands/version.js.test.cjs
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/config/definitions.js.test.cjs
  tap-snapshots/test/lib/utils/config/describe-all.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/lib/commands/version.js
Labels: semver:minor, Release 8.x, Release-Next

#4607 fix: 100% coverage in tests
  .github/workflows/ci.yml
  lib/base-command.js
  lib/utils/usage.js
  package.json
  scripts/config-doc-command.js
  tap-snapshots/test/lib/load-all-commands.js.test.cjs
  tap-snapshots/test/lib/utils/npm-usage.js.test.cjs
  test/coverage-map.js
  test/lib/commands/access.js
  test/lib/commands/cache.js
  test/lib/commands/diff.js
  test/lib/commands/init.js
  test/lib/commands/owner.js
  test/lib/commands/profile.js
  test/lib/commands/search.js
  test/lib/commands/star.js
  test/lib/commands/stars.js
  test/lib/commands/team.js
  test/lib/commands/unpublish.js
  test/lib/commands/update.js
  test/lib/load-all.js
Labels: semver:patch, Release 8.x, Release-Next
